### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by justjoheinz** [koudelka/visualixir#27]
When trying to install the assests via npm install I get:

```
   elixir-0:  Error: No compatible version found: phoenix_html@'file:../deps/phoenix_html'
    elixir-0: npm
    elixir-0:  
    elixir-0: ERR!
    elixir-0:  Valid install targets:
    elixir-0: npm
    elixir-0:  
    elixir-0: ERR!
    elixir-0:  ["2.10.4","2.12.0","2.13.2"]
    elixir-0: npm
    elixir-0:  
    elixir-0: ERR!
    elixir-0:      at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
    elixir-0: npm
    elixir-0:  
    elixir-0: ERR!
    elixir-0:      at /usr/share/npm/lib/cache.js:638:10
    elixir-0: npm
    elixir-0:  
    elixir-0: ERR!
    elixir-0:      at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
    elixir-0: npm
    elixir-0:  
    elixir-0: ERR!
    elixir-0:      at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
    elixir-0: npm
    elixir-0:  
    elixir-0: ERR!
    elixir-0:      at Object.oncomplete (fs.js:107:15)
    elixir-0: npm
    elixir-0:  
    elixir-0: ERR!
    elixir-0:  If you need help, you may report this log at:
    elixir-0: npm
    elixir-0:  
    elixir-0: ERR!     <http://github.com/isaacs/npm/issues>
    elixir-0: npm ERR! or email it to:
    elixir-0: npm ERR!     <npm-@googlegroups.com>
    elixir-0: 
    elixir-0: npm ERR! System Linux 3.13.0-170-generic
    elixir-0: npm
    elixir-0:  
    elixir-0: ERR!
    elixir-0:  
    elixir-0: command
    elixir-0:  "/usr/bin/nodejs" "/usr/bin/npm" "install"
    elixir-0: npm
    elixir-0:  ERR! cwd /home/vagrant/visualixir/assets
    elixir-0: npm ERR! node -v v0.10.25
    elixir-0: npm ERR! npm -v 1.3.10
    elixir-0: npm
```

This happens on Mac OS X as well as (this stacktrace) a vagrant ubuntu/trusty64 box.
